Numpy is a fundamental library for scientific computing in python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures

In [3]:
#Install the library
!pip install numpy


[notice] A new release of pip is available: 23.2.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
#Load the library
import numpy as np

In [5]:
#create array using numpy
#create a 1D Array
arr1 = np.array([1,2,3,4,5])
print (arr1)

[1 2 3 4 5]


In [6]:
#Type 
print(type(arr1))

<class 'numpy.ndarray'>


In [7]:
#Shape
print(arr1.shape)

(5,)


In [10]:
#Reshape into 2D Array
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)


array([[1, 2, 3, 4, 5]])

In [11]:
#Manual Create
arr2 = np.array ([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [12]:
#2D Array
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2)

[[1 2 3 4 5]
 [2 3 4 5 6]]


In [13]:
#Shape of arr2
print(arr2.shape)

(2, 5)


In [15]:
#Manual Random Array
np.arange(0,10,2) # Included 0, excluded10, 0 to 10, by +2

array([0, 2, 4, 6, 8])

In [17]:
#convert it into 2D
np.arange(0,10,2).reshape(5,1) #5 rows and 1 column


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [19]:
#all 1 included array
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [21]:
#Identity Metrix
np.eye(3) #Diagonal should be 1 and rest of elements are 0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
#Attributes of Numpy Array
arr = np.array([[1,2,3],[4,5,6]])

print("Array: \n", arr)
print("Shape: ", arr.shape)
print("Number of Dimensions: ", arr.ndim)
print("Size(Number of Elements): ", arr.size)
print("Data Type: ", arr.dtype)
print("Item Size(in bytes): ", arr.itemsize)

Array: 
 [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)
Number of Dimensions:  2
Size(Number of Elements):  6
Data Type:  int64
Item Size(in bytes):  8


In [44]:
#Numpy Vectorized Operation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

#Element wise Addition
print("Addition: ", arr1+arr2)
#Element wise Substraction
print("Addition: ", arr1-arr2)
#Element wise Multiplication
print("Addition: ", arr1*arr2)
#Element wise Division
print("Addition: ", arr1/arr2)

Addition:  [11 22 33 44 55]
Addition:  [ -9 -18 -27 -36 -45]
Addition:  [ 10  40  90 160 250]
Addition:  [0.1 0.1 0.1 0.1 0.1]


In [48]:
#Universal Function
arr = np.array([2,3,4,5,6])

#Square Root
print("Square Roots: ", np.sqrt(arr))
#Exponential
print("Exponential: ", np.exp(arr))
#sine
print("Sines: ", np.sin(arr))
#Natural Log
print("Logs: ", np.log(arr))


Square Roots:  [1.41421356 1.73205081 2.         2.23606798 2.44948974]
Exponential:  [  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
Sines:  [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
Logs:  [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [57]:
#Array Slicing and indexing
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print("Array: \n", arr)

#First Row
print("First Row: \n",arr[0])
#First Element - 1st row 1st column
print("First Element: ",arr[0][0])
#7,8,11,12
print(arr[1: ,2: ])

#Modify Array Element
arr[0,0] = 100
print(arr)

arr[1: ] = 100
print("\n", arr)

Array: 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First Row: 
 [1 2 3 4]
First Element:  1
[[ 7  8]
 [11 12]]
[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]

 [[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [58]:
#Ex- Statistical Concept:
#To have a mean of 0 and standard deviation of 1
data = np.array([1,2,3,4,5])

#Calculate the mean and standard deviation and variance
mean = np.mean(data)
std_dev = np.std(data)
variance = np.var(data)

#Normalize The Data
normalized_data = (data - mean) / std_dev

print("Normalized Data: ", normalized_data)


Normalized Data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [63]:
#Logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])

print(data>5)

print(data[data>5])

print(data[(data>=5) & (data<=8)])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[5 6 7 8]
